// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/goplus/spx"

const _ = true

type Jaime struct {
	spx.Sprite
	*Game
}
type Kai struct {
	spx.Sprite
	*Game
}
type Game struct {
	spx.Game
}
//line tutorial/01-Weather/Jaime.spx:1
func (this *Jaime) Main() {
//line tutorial/01-Weather/Jaime.spx:1:1
	this.OnMsg__1("1", func() {
//line tutorial/01-Weather/Jaime.spx:2:1
		this.Say("I come from \nEngland. aaaaa", 1)
//line tutorial/01-Weather/Jaime.spx:3:1
		this.Broadcast__0("2")
	})
//line tutorial/01-Weather/Jaime.spx:6:1
	this.OnMsg__1("3", func() {
//line tutorial/01-Weather/Jaime.spx:7:1
		this.Say("It's mild, \nbut it's not always\n\n\n pleasant.", 1)
//line tutorial/01-Weather/Jaime.spx:8:1
		this.NextCostume()
//line tutorial/01-Weather/Jaime.spx:9:1
		this.Say("The weather's often cold\n in the North and\n windy in the East.", 1)
//line tutorial/01-Weather/Jaime.spx:10:1
		this.Say("It's often wet in the West\n and sometimes warm in the South.", 1)
//line tutorial/01-Weather/Jaime.spx:11:1
		this.Broadcast__0("4")
	})
//line tutorial/01-Weather/Jaime.spx:14:1
	this.OnMsg__1("5", func() {
//line tutorial/01-Weather/Jaime.spx:15:1
		this.NextCostume()
//line tutorial/01-Weather/Jaime.spx:16:1
		this.Say("I like spring and summer.", 1)
//line tutorial/01-Weather/Jaime.spx:17:1
		this.Say("The days are long and\n the nights are short.", 1)
//line tutorial/01-Weather/Jaime.spx:18:1
		this.Say("The sun rises early and\n sets late. ", 1)
//line tutorial/01-Weather/Jaime.spx:19:1
		this.NextCostume()
//line tutorial/01-Weather/Jaime.spx:20:1
		this.Say("I don't like autumn and winter.", 1)
//line tutorial/01-Weather/Jaime.spx:21:1
		this.Say("The days are short and\n the nights are long.", 1)
//line tutorial/01-Weather/Jaime.spx:22:1
		this.Say("The sun rises late and\n sets early.", 1)
//line tutorial/01-Weather/Jaime.spx:23:1
		this.NextCostume()
//line tutorial/01-Weather/Jaime.spx:24:1
		this.Say("Our climate is not very good,\n but it's certainly interesting.", 1)
//line tutorial/01-Weather/Jaime.spx:25:1
		this.Say("It's our favourite subject\n of conversation.", 1)
//line tutorial/01-Weather/Jaime.spx:26:1
		this.Broadcast__0("6")
	})
//line tutorial/01-Weather/Jaime.spx:29:1
	this.OnMsg__1("7", func() {
//line tutorial/01-Weather/Jaime.spx:30:1
		this.Say("Bye!", 2)
//line tutorial/01-Weather/Jaime.spx:31:1
		this.NextCostume()
	})
}
func (this *Jaime) Classfname() string {
	return "Jaime"
}
//line tutorial/01-Weather/Kai.spx:1
func (this *Kai) Main() {
//line tutorial/01-Weather/Kai.spx:1:1
	this.OnStart(func() {
//line tutorial/01-Weather/Kai.spx:2:1
		this.Say("Where do you come from?", 1)
//line tutorial/01-Weather/Kai.spx:3:1
		this.Broadcast__0("1")
	})
//line tutorial/01-Weather/Kai.spx:6:1
	this.OnMsg__1("2", func() {
//line tutorial/01-Weather/Kai.spx:7:1
		this.Say("What's the climate like\n in your country?", 1)
//line tutorial/01-Weather/Kai.spx:8:1
		this.Broadcast__0("3")
	})
//line tutorial/01-Weather/Kai.spx:11:1
	this.OnMsg__1("4", func() {
//line tutorial/01-Weather/Kai.spx:12:1
		this.Say("Which seasons do you like best?", 1)
//line tutorial/01-Weather/Kai.spx:13:1
		this.Broadcast__0("5")
	})
//line tutorial/01-Weather/Kai.spx:16:1
	this.OnMsg__1("6", func() {
//line tutorial/01-Weather/Kai.spx:17:1
		this.Say("Thanks. Bye!", 2)
//line tutorial/01-Weather/Kai.spx:18:1
		this.NextCostume()
//line tutorial/01-Weather/Kai.spx:19:1
		this.Broadcast__0("7")
	})
}
func (this *Kai) Classfname() string {
	return "Kai"
}
func (this *Game) Main() {
	spx.Gopt_Game_Main(this, new(Jaime), new(Kai))
}
func main() {
	new(Game).Main()
}
