// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/goplus/spx"

const _ = true

type Bullet struct {
	spx.Sprite
	*Game
}
type SmallEnemy struct {
	spx.Sprite
	*Game
	life int
}
type Game struct {
	spx.Game
	explode spx.Sound
}

func (this *Game) MainEntry() {
}
func (this *Game) Main() {
	spx.Gopt_Game_Main(this, new(Bullet), new(SmallEnemy))
}
//line Bullet.spx:1
func (this *Bullet) Main() {
//line Bullet.spx:1:1
	this.OnTouched__1(func() {
//line Bullet.spx:2:1
		this.Destroy()
	})
//line Bullet.spx:5:1
	this.OnStart(func() {
//line Bullet.spx:6:1
		for {
			spx.Sched()
//line Bullet.spx:7:1
			this.Wait(0.1)
//line Bullet.spx:8:1
			spx.Gopt_Sprite_Clone__0(this)
		}
	})
//line Bullet.spx:12:1
	this.OnCloned__1(func() {
//line Bullet.spx:13:1
		this.SetXYpos(this.MouseX(), this.MouseY())
//line Bullet.spx:14:1
		this.Show()
//line Bullet.spx:15:1
		for {
			spx.Sched()
//line Bullet.spx:16:1
			this.Wait(0.01)
//line Bullet.spx:17:1
			this.Step__0(6)
//line Bullet.spx:18:1
			if this.Ypos() > 380 {
//line Bullet.spx:19:1
				this.Destroy()
			}
		}
	})
}
func (this *Bullet) Classfname() string {
	return "Bullet"
}
//line SmallEnemy.spx:4
func (this *SmallEnemy) Main() {
//line SmallEnemy.spx:4:1
	this.OnStart(func() {
//line SmallEnemy.spx:5:1
		for {
			spx.Sched()
//line SmallEnemy.spx:6:1
			this.Wait(0.3)
//line SmallEnemy.spx:7:1
			spx.Gopt_Sprite_Clone__0(this)
		}
	})
//line SmallEnemy.spx:11:1
	this.OnCloned__1(func() {
//line SmallEnemy.spx:12:1
		this.life = 2
	})
//line SmallEnemy.spx:15:1
	this.OnCloned__1(func() {
//line SmallEnemy.spx:16:1
		this.SetXYpos(spx.Rand__0(-160, 160), 380)
//line SmallEnemy.spx:17:1
		this.Show()
//line SmallEnemy.spx:18:1
		for {
			spx.Sched()
//line SmallEnemy.spx:19:1
			this.Wait(0.05)
//line SmallEnemy.spx:20:1
			this.ChangeYpos(-2.4)
//line SmallEnemy.spx:21:1
			if this.Ypos() < -280 {
//line SmallEnemy.spx:22:1
				this.Destroy()
			}
		}
	})
//line SmallEnemy.spx:28:1
	this.OnTouched__0(func(Bullet *spx.Sprite) {
//line SmallEnemy.spx:29:1
		this.life--
//line SmallEnemy.spx:30:1
		if this.life == 0 {
//line SmallEnemy.spx:31:1
			this.Die()
		}
	})
}
func (this *SmallEnemy) Classfname() string {
	return "SmallEnemy"
}
func main() {
	new(Game).Main()
}
