// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/goplus/spx"

const _ = true

type Bullet struct {
	spx.Sprite
	*Game
}
type SmallEnemy struct {
	spx.Sprite
	*Game
}
type Game struct {
	spx.Game
}

func (this *Game) MainEntry() {
}
func (this *Game) Main() {
	spx.Gopt_Game_Main(this, new(Bullet), new(SmallEnemy))
}
//line tutorial/05-Animation/Bullet.spx:1
func (this *Bullet) Main() {
//line tutorial/05-Animation/Bullet.spx:1:1
	this.OnTouched__1(func() {
//line tutorial/05-Animation/Bullet.spx:2:1
		this.Destroy()
	})
//line tutorial/05-Animation/Bullet.spx:5:1
	this.OnStart(func() {
		count :=0
//line tutorial/05-Animation/Bullet.spx:6:1
		for {
			spx.Sched()
//line tutorial/05-Animation/Bullet.spx:7:1
			this.Wait(1)
//line tutorial/05-Animation/Bullet.spx:8:1
			spx.Gopt_Sprite_Clone__0(this)
			count++
		}
	})
//line tutorial/05-Animation/Bullet.spx:12:1
	this.OnCloned__1(func() {
		this.SetXYpos(this.MouseX(), this.MouseY())
//line tutorial/05-Animation/Bullet.spx:13:1
//line tutorial/05-Animation/Bullet.spx:14:1
		this.Show()
//line tutorial/05-Animation/Bullet.spx:15:1
		for {
			spx.Sched()
//line tutorial/05-Animation/Bullet.spx:16:1
			this.Wait(0.04)
//line tutorial/05-Animation/Bullet.spx:17:1
			this.Step__0(2)
//line tutorial/05-Animation/Bullet.spx:18:1
			if this.Ypos() > 180 {
//line tutorial/05-Animation/Bullet.spx:19:1
				this.Destroy()
			}
		}
	})
}
func (this *Bullet) Classfname() string {
	return "Bullet"
}
//line tutorial/05-Animation/SmallEnemy.spx:1
func (this *SmallEnemy) Main() {
//line tutorial/05-Animation/SmallEnemy.spx:1:1
	this.OnStart(func() {
		this.SetXYpos(-100, 237)
//line tutorial/05-Animation/SmallEnemy.spx:2:1
//line tutorial/05-Animation/SmallEnemy.spx:3:1
		for {
			spx.Sched()
//line tutorial/05-Animation/SmallEnemy.spx:4:1
			this.Wait(3)
//line tutorial/05-Animation/SmallEnemy.spx:5:1
			spx.Gopt_Sprite_Clone__0(this)
		}
	})
//line tutorial/05-Animation/SmallEnemy.spx:9:1
	this.OnCloned__1(func() {
//line tutorial/05-Animation/SmallEnemy.spx:10:1
		this.SetXYpos(spx.Rand__0(-131, 131), 237)
//line tutorial/05-Animation/SmallEnemy.spx:11:1
		this.Show()
//line tutorial/05-Animation/SmallEnemy.spx:12:1
		for {
			spx.Sched()
//line tutorial/05-Animation/SmallEnemy.spx:13:1
			this.Wait(0.05)
//line tutorial/05-Animation/SmallEnemy.spx:14:1
			this.ChangeYpos(-2.4)
//line tutorial/05-Animation/SmallEnemy.spx:15:1
			if this.Touching(spx.EdgeBottom) {
//line tutorial/05-Animation/SmallEnemy.spx:16:1
				this.Destroy()
			}
		}
	})
//line tutorial/05-Animation/SmallEnemy.spx:21:1
	this.OnCloned__1(func() {
//line tutorial/05-Animation/SmallEnemy.spx:22:1
		life := 1
//line tutorial/05-Animation/SmallEnemy.spx:23:1
		for {
			spx.Sched()
//line tutorial/05-Animation/SmallEnemy.spx:24:1
			this.Wait(0.05)
//line tutorial/05-Animation/SmallEnemy.spx:25:1
			if this.Touching("Bullet") {
//line tutorial/05-Animation/SmallEnemy.spx:26:1
				life--
//line tutorial/05-Animation/SmallEnemy.spx:27:1
				if life == 0 {
//line tutorial/05-Animation/SmallEnemy.spx:28:1
					this.Die()
				}
			}
		}
	})
}
func (this *SmallEnemy) Classfname() string {
	return "SmallEnemy"
}
func main() {
	new(Game).Main()
}
