/*------------------------------------------------------------------------------
//   This code was generated by gdspx template sync.gen.go.tmpl.  
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//----------------------------------------------------------------------------*/

package engine

import (
	. "github.com/realdream-ai/gdspx/pkg/engine"
)


// IAudioMgr
func SyncAudioStopAll(){
	WaitMainThread()
	AudioMgr.StopAll()
}
func SyncAudioPlaySfx(path string){
	WaitMainThread()
	AudioMgr.PlaySfx(path)
}
func SyncAudioPlayMusic(path string){
	WaitMainThread()
	AudioMgr.PlayMusic(path)
}
func SyncAudioPauseMusic(){
	WaitMainThread()
	AudioMgr.PauseMusic()
}
func SyncAudioResumeMusic(){
	WaitMainThread()
	AudioMgr.ResumeMusic()
}
func SyncAudioGetMusicTimer() float32 {
	WaitMainThread()
	return AudioMgr.GetMusicTimer()
}
func SyncAudioSetMusicTimer(time float32){
	WaitMainThread()
	AudioMgr.SetMusicTimer(time)
}
func SyncAudioIsMusicPlaying() bool {
	WaitMainThread()
	return AudioMgr.IsMusicPlaying()
}
func SyncAudioSetSfxVolume(volume float32){
	WaitMainThread()
	AudioMgr.SetSfxVolume(volume)
}
func SyncAudioGetSfxVolume() float32 {
	WaitMainThread()
	return AudioMgr.GetSfxVolume()
}
func SyncAudioSetMusicVolume(volume float32){
	WaitMainThread()
	AudioMgr.SetMusicVolume(volume)
}
func SyncAudioGetMusicVolume() float32 {
	WaitMainThread()
	return AudioMgr.GetMusicVolume()
}
func SyncAudioSetMasterVolume(volume float32){
	WaitMainThread()
	AudioMgr.SetMasterVolume(volume)
}
func SyncAudioGetMasterVolume() float32 {
	WaitMainThread()
	return AudioMgr.GetMasterVolume()
} 

// ICameraMgr
func SyncCameraGetCameraPosition() Vec2 {
	WaitMainThread()
	return CameraMgr.GetCameraPosition()
}
func SyncCameraSetCameraPosition(position Vec2){
	WaitMainThread()
	CameraMgr.SetCameraPosition(position)
}
func SyncCameraGetCameraZoom() Vec2 {
	WaitMainThread()
	return CameraMgr.GetCameraZoom()
}
func SyncCameraSetCameraZoom(size Vec2){
	WaitMainThread()
	CameraMgr.SetCameraZoom(size)
}
func SyncCameraGetViewportRect() Rect2 {
	WaitMainThread()
	return CameraMgr.GetViewportRect()
} 

// IInputMgr
func SyncInputGetMousePos() Vec2 {
	WaitMainThread()
	return InputMgr.GetMousePos()
}
func SyncInputGetKey(key int64) bool {
	WaitMainThread()
	return InputMgr.GetKey(key)
}
func SyncInputGetMouseState(mouse_id int64) bool {
	WaitMainThread()
	return InputMgr.GetMouseState(mouse_id)
}
func SyncInputGetKeyState(key int64) int64 {
	WaitMainThread()
	return InputMgr.GetKeyState(key)
}
func SyncInputGetAxis(neg_action string, pos_action string) float32 {
	WaitMainThread()
	return InputMgr.GetAxis(neg_action, pos_action)
}
func SyncInputIsActionPressed(action string) bool {
	WaitMainThread()
	return InputMgr.IsActionPressed(action)
}
func SyncInputIsActionJustPressed(action string) bool {
	WaitMainThread()
	return InputMgr.IsActionJustPressed(action)
}
func SyncInputIsActionJustReleased(action string) bool {
	WaitMainThread()
	return InputMgr.IsActionJustReleased(action)
} 

// IPhysicMgr
func SyncPhysicRaycast(from Vec2, to Vec2, collision_mask int64) Object {
	WaitMainThread()
	return PhysicMgr.Raycast(from, to, collision_mask)
}
func SyncPhysicCheckCollision(from Vec2, to Vec2, collision_mask int64, collide_with_areas bool, collide_with_bodies bool) bool {
	WaitMainThread()
	return PhysicMgr.CheckCollision(from, to, collision_mask, collide_with_areas, collide_with_bodies)
}
func SyncPhysicCheckTouchedCameraBoundary(obj Object, board_type int64) bool {
	WaitMainThread()
	return PhysicMgr.CheckTouchedCameraBoundary(obj, board_type)
} 

// IPlatformMgr
func SyncPlatformSetWindowPosition(pos Vec2){
	WaitMainThread()
	PlatformMgr.SetWindowPosition(pos)
}
func SyncPlatformGetWindowPosition() Vec2 {
	WaitMainThread()
	return PlatformMgr.GetWindowPosition()
}
func SyncPlatformSetWindowSize(width int64, height int64){
	WaitMainThread()
	PlatformMgr.SetWindowSize(width, height)
}
func SyncPlatformGetWindowSize() Vec2 {
	WaitMainThread()
	return PlatformMgr.GetWindowSize()
}
func SyncPlatformSetWindowTitle(title string){
	WaitMainThread()
	PlatformMgr.SetWindowTitle(title)
}
func SyncPlatformGetWindowTitle() string {
	WaitMainThread()
	return PlatformMgr.GetWindowTitle()
}
func SyncPlatformSetWindowFullscreen(enable bool){
	WaitMainThread()
	PlatformMgr.SetWindowFullscreen(enable)
}
func SyncPlatformIsWindowFullscreen() bool {
	WaitMainThread()
	return PlatformMgr.IsWindowFullscreen()
}
func SyncPlatformSetDebugMode(enable bool){
	WaitMainThread()
	PlatformMgr.SetDebugMode(enable)
}
func SyncPlatformIsDebugMode() bool {
	WaitMainThread()
	return PlatformMgr.IsDebugMode()
}
func SyncPlatformGetTimeScale() float32 {
	WaitMainThread()
	return PlatformMgr.GetTimeScale()
}
func SyncPlatformSetTimeScale(time_scale float32){
	WaitMainThread()
	PlatformMgr.SetTimeScale(time_scale)
} 

// IResMgr
func SyncResSetLoadMode(is_direct_mode bool){
	WaitMainThread()
	ResMgr.SetLoadMode(is_direct_mode)
}
func SyncResGetLoadMode() bool {
	WaitMainThread()
	return ResMgr.GetLoadMode()
}
func SyncResGetBoundFromAlpha(p_path string) Rect2 {
	WaitMainThread()
	return ResMgr.GetBoundFromAlpha(p_path)
}
func SyncResGetImageSize(p_path string) Vec2 {
	WaitMainThread()
	return ResMgr.GetImageSize(p_path)
}
func SyncResReadAllText(p_path string) string {
	WaitMainThread()
	return ResMgr.ReadAllText(p_path)
}
func SyncResHasFile(p_path string) bool {
	WaitMainThread()
	return ResMgr.HasFile(p_path)
} 

// ISceneMgr
func SyncSceneChangeSceneToFile(path string){
	WaitMainThread()
	SceneMgr.ChangeSceneToFile(path)
}
func SyncSceneReloadCurrentScene() int64 {
	WaitMainThread()
	return SceneMgr.ReloadCurrentScene()
}
func SyncSceneUnloadCurrentScene(){
	WaitMainThread()
	SceneMgr.UnloadCurrentScene()
} 

// ISpriteMgr
func SyncSpriteSetDontDestroyOnLoad(obj Object){
	WaitMainThread()
	SpriteMgr.SetDontDestroyOnLoad(obj)
}
func SyncSpriteSetProcess(obj Object, is_on bool){
	WaitMainThread()
	SpriteMgr.SetProcess(obj, is_on)
}
func SyncSpriteSetPhysicProcess(obj Object, is_on bool){
	WaitMainThread()
	SpriteMgr.SetPhysicProcess(obj, is_on)
}
func SyncSpriteSetChildPosition(obj Object, path string, pos Vec2){
	WaitMainThread()
	SpriteMgr.SetChildPosition(obj, path, pos)
}
func SyncSpriteGetChildPosition(obj Object, path string) Vec2 {
	WaitMainThread()
	return SpriteMgr.GetChildPosition(obj, path)
}
func SyncSpriteSetChildRotation(obj Object, path string, rot float32){
	WaitMainThread()
	SpriteMgr.SetChildRotation(obj, path, rot)
}
func SyncSpriteGetChildRotation(obj Object, path string) float32 {
	WaitMainThread()
	return SpriteMgr.GetChildRotation(obj, path)
}
func SyncSpriteSetChildScale(obj Object, path string, scale Vec2){
	WaitMainThread()
	SpriteMgr.SetChildScale(obj, path, scale)
}
func SyncSpriteGetChildScale(obj Object, path string) Vec2 {
	WaitMainThread()
	return SpriteMgr.GetChildScale(obj, path)
}
func SyncSpriteCheckCollision(obj Object, target Object, is_src_trigger bool, is_dst_trigger bool) bool {
	WaitMainThread()
	return SpriteMgr.CheckCollision(obj, target, is_src_trigger, is_dst_trigger)
}
func SyncSpriteCheckCollisionWithPoint(obj Object, point Vec2, is_trigger bool) bool {
	WaitMainThread()
	return SpriteMgr.CheckCollisionWithPoint(obj, point, is_trigger)
}
func SyncSpriteCreateSprite(path string) Object {
	WaitMainThread()
	return SpriteMgr.CreateSprite(path)
}
func SyncSpriteCloneSprite(obj Object) Object {
	WaitMainThread()
	return SpriteMgr.CloneSprite(obj)
}
func SyncSpriteDestroySprite(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.DestroySprite(obj)
}
func SyncSpriteIsSpriteAlive(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsSpriteAlive(obj)
}
func SyncSpriteSetPosition(obj Object, pos Vec2){
	WaitMainThread()
	SpriteMgr.SetPosition(obj, pos)
}
func SyncSpriteGetPosition(obj Object) Vec2 {
	WaitMainThread()
	return SpriteMgr.GetPosition(obj)
}
func SyncSpriteSetRotation(obj Object, rot float32){
	WaitMainThread()
	SpriteMgr.SetRotation(obj, rot)
}
func SyncSpriteGetRotation(obj Object) float32 {
	WaitMainThread()
	return SpriteMgr.GetRotation(obj)
}
func SyncSpriteSetScale(obj Object, scale Vec2){
	WaitMainThread()
	SpriteMgr.SetScale(obj, scale)
}
func SyncSpriteGetScale(obj Object) Vec2 {
	WaitMainThread()
	return SpriteMgr.GetScale(obj)
}
func SyncSpriteSetRenderScale(obj Object, scale Vec2){
	WaitMainThread()
	SpriteMgr.SetRenderScale(obj, scale)
}
func SyncSpriteGetRenderScale(obj Object) Vec2 {
	WaitMainThread()
	return SpriteMgr.GetRenderScale(obj)
}
func SyncSpriteSetColor(obj Object, color Color){
	WaitMainThread()
	SpriteMgr.SetColor(obj, color)
}
func SyncSpriteGetColor(obj Object) Color {
	WaitMainThread()
	return SpriteMgr.GetColor(obj)
}
func SyncSpriteSetTextureAltas(obj Object, path string, rect2 Rect2){
	WaitMainThread()
	SpriteMgr.SetTextureAltas(obj, path, rect2)
}
func SyncSpriteSetTexture(obj Object, path string){
	WaitMainThread()
	SpriteMgr.SetTexture(obj, path)
}
func SyncSpriteGetTexture(obj Object) string {
	WaitMainThread()
	return SpriteMgr.GetTexture(obj)
}
func SyncSpriteSetVisible(obj Object, visible bool){
	WaitMainThread()
	SpriteMgr.SetVisible(obj, visible)
}
func SyncSpriteGetVisible(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.GetVisible(obj)
}
func SyncSpriteGetZIndex(obj Object) int64 {
	WaitMainThread()
	return SpriteMgr.GetZIndex(obj)
}
func SyncSpriteSetZIndex(obj Object, z int64){
	WaitMainThread()
	SpriteMgr.SetZIndex(obj, z)
}
func SyncSpritePlayAnim(obj Object, p_name string, p_custom_scale float32, p_from_end bool){
	WaitMainThread()
	SpriteMgr.PlayAnim(obj, p_name, p_custom_scale, p_from_end)
}
func SyncSpritePlayBackwardsAnim(obj Object, p_name string){
	WaitMainThread()
	SpriteMgr.PlayBackwardsAnim(obj, p_name)
}
func SyncSpritePauseAnim(obj Object){
	WaitMainThread()
	SpriteMgr.PauseAnim(obj)
}
func SyncSpriteStopAnim(obj Object){
	WaitMainThread()
	SpriteMgr.StopAnim(obj)
}
func SyncSpriteIsPlayingAnim(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsPlayingAnim(obj)
}
func SyncSpriteSetAnim(obj Object, p_name string){
	WaitMainThread()
	SpriteMgr.SetAnim(obj, p_name)
}
func SyncSpriteGetAnim(obj Object) string {
	WaitMainThread()
	return SpriteMgr.GetAnim(obj)
}
func SyncSpriteSetAnimFrame(obj Object, p_frame int64){
	WaitMainThread()
	SpriteMgr.SetAnimFrame(obj, p_frame)
}
func SyncSpriteGetAnimFrame(obj Object) int64 {
	WaitMainThread()
	return SpriteMgr.GetAnimFrame(obj)
}
func SyncSpriteSetAnimSpeedScale(obj Object, p_speed_scale float32){
	WaitMainThread()
	SpriteMgr.SetAnimSpeedScale(obj, p_speed_scale)
}
func SyncSpriteGetAnimSpeedScale(obj Object) float32 {
	WaitMainThread()
	return SpriteMgr.GetAnimSpeedScale(obj)
}
func SyncSpriteGetAnimPlayingSpeed(obj Object) float32 {
	WaitMainThread()
	return SpriteMgr.GetAnimPlayingSpeed(obj)
}
func SyncSpriteSetAnimCentered(obj Object, p_center bool){
	WaitMainThread()
	SpriteMgr.SetAnimCentered(obj, p_center)
}
func SyncSpriteIsAnimCentered(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsAnimCentered(obj)
}
func SyncSpriteSetAnimOffset(obj Object, p_offset Vec2){
	WaitMainThread()
	SpriteMgr.SetAnimOffset(obj, p_offset)
}
func SyncSpriteGetAnimOffset(obj Object) Vec2 {
	WaitMainThread()
	return SpriteMgr.GetAnimOffset(obj)
}
func SyncSpriteSetAnimFlipH(obj Object, p_flip bool){
	WaitMainThread()
	SpriteMgr.SetAnimFlipH(obj, p_flip)
}
func SyncSpriteIsAnimFlippedH(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsAnimFlippedH(obj)
}
func SyncSpriteSetAnimFlipV(obj Object, p_flip bool){
	WaitMainThread()
	SpriteMgr.SetAnimFlipV(obj, p_flip)
}
func SyncSpriteIsAnimFlippedV(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsAnimFlippedV(obj)
}
func SyncSpriteSetVelocity(obj Object, velocity Vec2){
	WaitMainThread()
	SpriteMgr.SetVelocity(obj, velocity)
}
func SyncSpriteGetVelocity(obj Object) Vec2 {
	WaitMainThread()
	return SpriteMgr.GetVelocity(obj)
}
func SyncSpriteIsOnFloor(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsOnFloor(obj)
}
func SyncSpriteIsOnFloorOnly(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsOnFloorOnly(obj)
}
func SyncSpriteIsOnWall(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsOnWall(obj)
}
func SyncSpriteIsOnWallOnly(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsOnWallOnly(obj)
}
func SyncSpriteIsOnCeiling(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsOnCeiling(obj)
}
func SyncSpriteIsOnCeilingOnly(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsOnCeilingOnly(obj)
}
func SyncSpriteGetLastMotion(obj Object) Vec2 {
	WaitMainThread()
	return SpriteMgr.GetLastMotion(obj)
}
func SyncSpriteGetPositionDelta(obj Object) Vec2 {
	WaitMainThread()
	return SpriteMgr.GetPositionDelta(obj)
}
func SyncSpriteGetFloorNormal(obj Object) Vec2 {
	WaitMainThread()
	return SpriteMgr.GetFloorNormal(obj)
}
func SyncSpriteGetWallNormal(obj Object) Vec2 {
	WaitMainThread()
	return SpriteMgr.GetWallNormal(obj)
}
func SyncSpriteGetRealVelocity(obj Object) Vec2 {
	WaitMainThread()
	return SpriteMgr.GetRealVelocity(obj)
}
func SyncSpriteMoveAndSlide(obj Object){
	WaitMainThread()
	SpriteMgr.MoveAndSlide(obj)
}
func SyncSpriteSetGravity(obj Object, gravity float32){
	WaitMainThread()
	SpriteMgr.SetGravity(obj, gravity)
}
func SyncSpriteGetGravity(obj Object) float32 {
	WaitMainThread()
	return SpriteMgr.GetGravity(obj)
}
func SyncSpriteSetMass(obj Object, mass float32){
	WaitMainThread()
	SpriteMgr.SetMass(obj, mass)
}
func SyncSpriteGetMass(obj Object) float32 {
	WaitMainThread()
	return SpriteMgr.GetMass(obj)
}
func SyncSpriteAddForce(obj Object, force Vec2){
	WaitMainThread()
	SpriteMgr.AddForce(obj, force)
}
func SyncSpriteAddImpulse(obj Object, impulse Vec2){
	WaitMainThread()
	SpriteMgr.AddImpulse(obj, impulse)
}
func SyncSpriteSetCollisionLayer(obj Object, layer int64){
	WaitMainThread()
	SpriteMgr.SetCollisionLayer(obj, layer)
}
func SyncSpriteGetCollisionLayer(obj Object) int64 {
	WaitMainThread()
	return SpriteMgr.GetCollisionLayer(obj)
}
func SyncSpriteSetCollisionMask(obj Object, mask int64){
	WaitMainThread()
	SpriteMgr.SetCollisionMask(obj, mask)
}
func SyncSpriteGetCollisionMask(obj Object) int64 {
	WaitMainThread()
	return SpriteMgr.GetCollisionMask(obj)
}
func SyncSpriteSetTriggerLayer(obj Object, layer int64){
	WaitMainThread()
	SpriteMgr.SetTriggerLayer(obj, layer)
}
func SyncSpriteGetTriggerLayer(obj Object) int64 {
	WaitMainThread()
	return SpriteMgr.GetTriggerLayer(obj)
}
func SyncSpriteSetTriggerMask(obj Object, mask int64){
	WaitMainThread()
	SpriteMgr.SetTriggerMask(obj, mask)
}
func SyncSpriteGetTriggerMask(obj Object) int64 {
	WaitMainThread()
	return SpriteMgr.GetTriggerMask(obj)
}
func SyncSpriteSetColliderRect(obj Object, center Vec2, size Vec2){
	WaitMainThread()
	SpriteMgr.SetColliderRect(obj, center, size)
}
func SyncSpriteSetColliderCircle(obj Object, center Vec2, radius float32){
	WaitMainThread()
	SpriteMgr.SetColliderCircle(obj, center, radius)
}
func SyncSpriteSetColliderCapsule(obj Object, center Vec2, size Vec2){
	WaitMainThread()
	SpriteMgr.SetColliderCapsule(obj, center, size)
}
func SyncSpriteSetCollisionEnabled(obj Object, enabled bool){
	WaitMainThread()
	SpriteMgr.SetCollisionEnabled(obj, enabled)
}
func SyncSpriteIsCollisionEnabled(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsCollisionEnabled(obj)
}
func SyncSpriteSetTriggerRect(obj Object, center Vec2, size Vec2){
	WaitMainThread()
	SpriteMgr.SetTriggerRect(obj, center, size)
}
func SyncSpriteSetTriggerCircle(obj Object, center Vec2, radius float32){
	WaitMainThread()
	SpriteMgr.SetTriggerCircle(obj, center, radius)
}
func SyncSpriteSetTriggerCapsule(obj Object, center Vec2, size Vec2){
	WaitMainThread()
	SpriteMgr.SetTriggerCapsule(obj, center, size)
}
func SyncSpriteSetTriggerEnabled(obj Object, trigger bool){
	WaitMainThread()
	SpriteMgr.SetTriggerEnabled(obj, trigger)
}
func SyncSpriteIsTriggerEnabled(obj Object) bool {
	WaitMainThread()
	return SpriteMgr.IsTriggerEnabled(obj)
} 

// IUiMgr
func SyncUiBindNode(obj Object, rel_path string) Object {
	WaitMainThread()
	return UiMgr.BindNode(obj, rel_path)
}
func SyncUiCreateNode(path string) Object {
	WaitMainThread()
	return UiMgr.CreateNode(path)
}
func SyncUiCreateButton(path string, text string) Object {
	WaitMainThread()
	return UiMgr.CreateButton(path, text)
}
func SyncUiCreateLabel(path string, text string) Object {
	WaitMainThread()
	return UiMgr.CreateLabel(path, text)
}
func SyncUiCreateImage(path string) Object {
	WaitMainThread()
	return UiMgr.CreateImage(path)
}
func SyncUiCreateToggle(path string, value bool) Object {
	WaitMainThread()
	return UiMgr.CreateToggle(path, value)
}
func SyncUiCreateSlider(path string, value float32) Object {
	WaitMainThread()
	return UiMgr.CreateSlider(path, value)
}
func SyncUiCreateInput(path string, text string) Object {
	WaitMainThread()
	return UiMgr.CreateInput(path, text)
}
func SyncUiDestroyNode(obj Object) bool {
	WaitMainThread()
	return UiMgr.DestroyNode(obj)
}
func SyncUiGetType(obj Object) int64 {
	WaitMainThread()
	return UiMgr.GetType(obj)
}
func SyncUiSetText(obj Object, text string){
	WaitMainThread()
	UiMgr.SetText(obj, text)
}
func SyncUiGetText(obj Object) string {
	WaitMainThread()
	return UiMgr.GetText(obj)
}
func SyncUiSetTexture(obj Object, path string){
	WaitMainThread()
	UiMgr.SetTexture(obj, path)
}
func SyncUiGetTexture(obj Object) string {
	WaitMainThread()
	return UiMgr.GetTexture(obj)
}
func SyncUiSetColor(obj Object, color Color){
	WaitMainThread()
	UiMgr.SetColor(obj, color)
}
func SyncUiGetColor(obj Object) Color {
	WaitMainThread()
	return UiMgr.GetColor(obj)
}
func SyncUiSetFontSize(obj Object, size int64){
	WaitMainThread()
	UiMgr.SetFontSize(obj, size)
}
func SyncUiGetFontSize(obj Object) int64 {
	WaitMainThread()
	return UiMgr.GetFontSize(obj)
}
func SyncUiSetVisible(obj Object, visible bool){
	WaitMainThread()
	UiMgr.SetVisible(obj, visible)
}
func SyncUiGetVisible(obj Object) bool {
	WaitMainThread()
	return UiMgr.GetVisible(obj)
}
func SyncUiSetInteractable(obj Object, interactable bool){
	WaitMainThread()
	UiMgr.SetInteractable(obj, interactable)
}
func SyncUiGetInteractable(obj Object) bool {
	WaitMainThread()
	return UiMgr.GetInteractable(obj)
}
func SyncUiSetRect(obj Object, rect Rect2){
	WaitMainThread()
	UiMgr.SetRect(obj, rect)
}
func SyncUiGetRect(obj Object) Rect2 {
	WaitMainThread()
	return UiMgr.GetRect(obj)
}
func SyncUiGetLayoutDirection(obj Object) int64 {
	WaitMainThread()
	return UiMgr.GetLayoutDirection(obj)
}
func SyncUiSetLayoutDirection(obj Object, value int64){
	WaitMainThread()
	UiMgr.SetLayoutDirection(obj, value)
}
func SyncUiGetLayoutMode(obj Object) int64 {
	WaitMainThread()
	return UiMgr.GetLayoutMode(obj)
}
func SyncUiSetLayoutMode(obj Object, value int64){
	WaitMainThread()
	UiMgr.SetLayoutMode(obj, value)
}
func SyncUiGetAnchorsPreset(obj Object) int64 {
	WaitMainThread()
	return UiMgr.GetAnchorsPreset(obj)
}
func SyncUiSetAnchorsPreset(obj Object, value int64){
	WaitMainThread()
	UiMgr.SetAnchorsPreset(obj, value)
}
func SyncUiGetScale(obj Object) Vec2 {
	WaitMainThread()
	return UiMgr.GetScale(obj)
}
func SyncUiSetScale(obj Object, value Vec2){
	WaitMainThread()
	UiMgr.SetScale(obj, value)
}
func SyncUiGetPosition(obj Object) Vec2 {
	WaitMainThread()
	return UiMgr.GetPosition(obj)
}
func SyncUiSetPosition(obj Object, value Vec2){
	WaitMainThread()
	UiMgr.SetPosition(obj, value)
}
func SyncUiGetSize(obj Object) Vec2 {
	WaitMainThread()
	return UiMgr.GetSize(obj)
}
func SyncUiSetSize(obj Object, value Vec2){
	WaitMainThread()
	UiMgr.SetSize(obj, value)
}
func SyncUiGetGlobalPosition(obj Object) Vec2 {
	WaitMainThread()
	return UiMgr.GetGlobalPosition(obj)
}
func SyncUiSetGlobalPosition(obj Object, value Vec2){
	WaitMainThread()
	UiMgr.SetGlobalPosition(obj, value)
}
func SyncUiGetRotation(obj Object) float32 {
	WaitMainThread()
	return UiMgr.GetRotation(obj)
}
func SyncUiSetRotation(obj Object, value float32){
	WaitMainThread()
	UiMgr.SetRotation(obj, value)
}
func SyncUiGetFlip(obj Object, horizontal bool) bool {
	WaitMainThread()
	return UiMgr.GetFlip(obj, horizontal)
}
func SyncUiSetFlip(obj Object, horizontal bool, is_flip bool){
	WaitMainThread()
	UiMgr.SetFlip(obj, horizontal, is_flip)
} 

