
function BindFFI(goBridge) {
    console.log("BindFFI   ====>", goBridge)
    var FFI = {}
    FFI.gdspx_on_engine_start = goBridge.getGoFunction("gdspx_on_engine_start")
    FFI.gdspx_on_engine_update = goBridge.getGoFunction("gdspx_on_engine_update")
    FFI.gdspx_on_engine_fixed_update = goBridge.getGoFunction("gdspx_on_engine_fixed_update")
    FFI.gdspx_on_engine_destroy = goBridge.getGoFunction("gdspx_on_engine_destroy")
    FFI.gdspx_on_scene_sprite_instantiated = goBridge.getGoFunction("gdspx_on_scene_sprite_instantiated")
    FFI.gdspx_on_sprite_ready = goBridge.getGoFunction("gdspx_on_sprite_ready")
    FFI.gdspx_on_sprite_updated = goBridge.getGoFunction("gdspx_on_sprite_updated")
    FFI.gdspx_on_sprite_fixed_updated = goBridge.getGoFunction("gdspx_on_sprite_fixed_updated")
    FFI.gdspx_on_sprite_destroyed = goBridge.getGoFunction("gdspx_on_sprite_destroyed")
    FFI.gdspx_on_sprite_frames_set_changed = goBridge.getGoFunction("gdspx_on_sprite_frames_set_changed")
    FFI.gdspx_on_sprite_animation_changed = goBridge.getGoFunction("gdspx_on_sprite_animation_changed")
    FFI.gdspx_on_sprite_frame_changed = goBridge.getGoFunction("gdspx_on_sprite_frame_changed")
    FFI.gdspx_on_sprite_animation_looped = goBridge.getGoFunction("gdspx_on_sprite_animation_looped")
    FFI.gdspx_on_sprite_animation_finished = goBridge.getGoFunction("gdspx_on_sprite_animation_finished")
    FFI.gdspx_on_sprite_vfx_finished = goBridge.getGoFunction("gdspx_on_sprite_vfx_finished")
    FFI.gdspx_on_sprite_screen_exited = goBridge.getGoFunction("gdspx_on_sprite_screen_exited")
    FFI.gdspx_on_sprite_screen_entered = goBridge.getGoFunction("gdspx_on_sprite_screen_entered")
    FFI.gdspx_on_mouse_pressed = goBridge.getGoFunction("gdspx_on_mouse_pressed")
    FFI.gdspx_on_mouse_released = goBridge.getGoFunction("gdspx_on_mouse_released")
    FFI.gdspx_on_key_pressed = goBridge.getGoFunction("gdspx_on_key_pressed")
    FFI.gdspx_on_key_released = goBridge.getGoFunction("gdspx_on_key_released")
    FFI.gdspx_on_action_pressed = goBridge.getGoFunction("gdspx_on_action_pressed")
    FFI.gdspx_on_action_just_pressed = goBridge.getGoFunction("gdspx_on_action_just_pressed")
    FFI.gdspx_on_action_just_released = goBridge.getGoFunction("gdspx_on_action_just_released")
    FFI.gdspx_on_axis_changed = goBridge.getGoFunction("gdspx_on_axis_changed")
    FFI.gdspx_on_collision_enter = goBridge.getGoFunction("gdspx_on_collision_enter")
    FFI.gdspx_on_collision_stay = goBridge.getGoFunction("gdspx_on_collision_stay")
    FFI.gdspx_on_collision_exit = goBridge.getGoFunction("gdspx_on_collision_exit")
    FFI.gdspx_on_trigger_enter = goBridge.getGoFunction("gdspx_on_trigger_enter")
    FFI.gdspx_on_trigger_stay = goBridge.getGoFunction("gdspx_on_trigger_stay")
    FFI.gdspx_on_trigger_exit = goBridge.getGoFunction("gdspx_on_trigger_exit")
    FFI.gdspx_on_ui_ready = goBridge.getGoFunction("gdspx_on_ui_ready")
    FFI.gdspx_on_ui_updated = goBridge.getGoFunction("gdspx_on_ui_updated")
    FFI.gdspx_on_ui_destroyed = goBridge.getGoFunction("gdspx_on_ui_destroyed")
    FFI.gdspx_on_ui_pressed = goBridge.getGoFunction("gdspx_on_ui_pressed")
    FFI.gdspx_on_ui_released = goBridge.getGoFunction("gdspx_on_ui_released")
    FFI.gdspx_on_ui_hovered = goBridge.getGoFunction("gdspx_on_ui_hovered")
    FFI.gdspx_on_ui_clicked = goBridge.getGoFunction("gdspx_on_ui_clicked")
    FFI.gdspx_on_ui_toggle = goBridge.getGoFunction("gdspx_on_ui_toggle")
    FFI.gdspx_on_ui_text_changed = goBridge.getGoFunction("gdspx_on_ui_text_changed")
    return FFI
}